import "./globals.css";
import Header from "@/Header";
import localFont from "next/font/local";
// AppRouterCacheProvider removed: not available in this Next.js version
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

// 사용할 로컬 폰트 이름 설정
const vitroInspire = localFont({
  src: "../public/fonts/vitroInspire.otf", // 폰트 파일 경로
  display: "swap",
  variable: "--font-your-font", // CSS 변수 이름 설정
});

export const metadata = {
  title: "Itescape",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={cn(
        "bg-[#3C465C]",
        vitroInspire.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <body>
        <AppRouterCacheProvider>
          <div className="bg-[#D9D9D9] px-10 border-b">
            <Header />
          </div>
          <main className="bg-[#3C465C]">{children}</main>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
